# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.provider "virtualbox" do |v|
        host = RbConfig::CONFIG['host_os']

        # Give VM 1/4 system memory 
        if host =~ /darwin/
            # sysctl returns Bytes and we need to convert to MB
            mem = `sysctl -n hw.memsize`.to_i / 1024
        elsif host =~ /linux/
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i 
        elsif host =~ /mswin|mingw|cygwin/
            # Windows code via https://github.com/rdsubhas/vagrant-faster
            mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
        end

        mem = mem / 1024 / 4
        v.customize ["modifyvm", :id, "--memory", mem]
    end

    config.vm.synced_folder "../", "/app"

    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provision "shell", path: "bootstrap.sh"
end
