# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.synced_folder "../", "/app"

    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provision "shell", path: "bootstrap.sh"
end
